# Site Settings
title: edinsolar.org
email: webmaster@edinsolar.org
description: "Edinsolar - University of Edinburgh Solar Car Project"
baseurl: ""
url: "http://edinsolar.org"
author: "Edinsolar"

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /
 - text: Team
   url: /team
 - text: News
   url: /news

# Build Settings
paginate: 12
paginate_path: "news/page:num"
markdown: kramdown
permalink: pretty
