# Site Settings
title: edinsolar.org
email: webmaster@edinsolar.org
description: "Edinsolar - Edinburgh University's Solar Racing Team. We’re designing and building a solar car to race in the 2017 World Solar Challenge in Australia."
baseurl: ""
url: "http://edinsolar.org"
author: "Edinsolar"

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /
 - text: Team
   url: /team
 - text: News
   url: /news

# Build Settings
paginate: 12
paginate_path: "news/page:num"
markdown: kramdown
permalink: pretty
